language: python

sudo: false

env:
    global:
        - LILYPOND_VERSION=2.19.65

python:
    - 3.5

before_install:
    - echo TRAVIS_PYTHON_VERSION $TRAVIS_PYTHON_VERSION
    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-$LILYPOND_VERSION-1.linux-64.sh
    - sh lilypond-$LILYPOND_VERSION-1.linux-64.sh --batch
    - export PATH=/home/travis/bin:$PATH
    - pip install -U pip

install:
    - pip install -e .

script:
    - ajv doctest ./demarest --diff
    - py.test -vv ./demarest

notifications:
    email: false
